### ISSUE TITLE
Generate Paths that can go backwards

### ISSUE THREAD

**Issue by aswerdlow935** [Milken-Computer-Science/MilkenKnights-PowerUp#11]
Both TrajectoryLib and Pathfinder do not seem to allow for backwards movement. Need to find a solution for going backwards while generating (hopefully more than just add a negative to the generated paths when needed).

**Comment by aswerdlow935** [comment]
Added Download Reverse Button to Lightning Path. Need to test what the actual robot behavior is (simply added a negative to position, velocity, acceleration and jerk)

**Comment by Leo428** [comment]
If we are driving backward, the path for right motor should be used for the left motor to turn and head correctly. Is this correct?

**Comment by alexanderswerdlow** [comment]
We found that either switching the left and right side AND/OR adding a negative to pos/vel/accel/jerk works. It's not ideal but we ended up just testing each segment to find the correct transformation

**Comment by Leo428** [comment]
Thanks for answering. I will test it on our robot this week.
