### ISSUE TITLE
Arm should stay in the same position after enable

### ISSUE THREAD

**Issue by aswerdlow935** [Milken-Computer-Science/MilkenKnights-PowerUp#16]

**Comment by aswerdlow935** [comment]
Arm stays in the same position after enable, but when moved (e.g. by gravity) after disable, it quickly shoots to previous position and trips current limit. Can't seem to find the bug.

**Comment by AustinShalit** [comment]
If using a can talon you might need to prevent the integrator from integrating while disabled.

**Comment by aswerdlow935** [comment]
Ahhhhh good idea....do you know what method I would use...configMaxIntegralAccumulator or setIntegralAccumulator? (Also I'm a bit confused as to what the parameters are)

**Comment by alexanderswerdlow** [comment]
So it turns out we actually never had any I (I had taken it out a few weeks ago)...but the problem still persists
