### ISSUE TITLE
Field Centric Turn-In-Place

### ISSUE THREAD

**Issue by aswerdlow935** [Milken-Computer-Science/MilkenKnights-PowerUp#4]
Add rotate in place using path following (with different PID constants) or motion magic. Assign 4 buttons to 0,90,180,and 270 degree angles.

**Comment by AustinShalit** [comment]
Remember that if you do this you also need a way to rezero the gyro during the match

**Comment by aswerdlow935** [comment]
🧐🤔Are you expecting the gyro angle to drift too much during the match?....if so..recommendations on how to rezero (other than a driver manually zeroing)

**Comment by AustinShalit** [comment]
Driver would need to have a button.  I am curious about the use case for this.  When does the driver need to be aligned to the field?

**Comment by aswerdlow935** [comment]
Yoel wanted it for easier alignment when intaking cubes and outaking cubes into the exchange. He wants it, but is not a huge priority so I think I'm gonna leave it on the backburner for now
