### ISSUE TITLE
Tune Path Follower

### ISSUE THREAD

**Issue by aswerdlow935** [Milken-Computer-Science/MilkenKnights-PowerUp#6]
Tune Path Follower kP, kA, and kAng to ensure accuracy and precision. Desired accuracy is +-0.5in and +-0.5deg

**Comment by aswerdlow935** [comment]
Effective_Wheelbase appears to be incorrect as without a kAng, the angle error can be as high as 20-30deg. A high kAng corrects this somewhat to ~5deg during turns but causes some instability. Need to try playing with the wheelbase and see if that helps. Furthermore, kA seems either be ineffective or cause instability (without it maximum velocity error during a run is ~5in/s), so more tuning/changes are needed

**Comment by AustinShalit** [comment]
This seems fishy... wheelbase is a physical constant, right?

**Comment by aswerdlow935** [comment]
So that's what I thought....I was reading some stuff on chief about different 'effective wheelbases' but not really sure. I just really can't think of another reason why turns would have such error margins. I considered acceleration and jerk numbers (those I mostly made up), but even after lowering them dramatically, similar behavior occurs. The underlying velocity control is pretty accurate and precise and responds quickly (with basically no steady state error) so I doubt it is that. Next time I test I'll go step by step and test each variable again but I'm assuming that the reason for the constant accuracy error during curve-paths is due to one of these factors. Running a simple 'switch' path translating from (0,0) to ~(110,82) I was getting a large angle error and a subsequent X error of ~6in and Y error of ~1in but it was extremely precise over many runs (+-1in)

**Comment by aswerdlow935** [comment]
Set individual kFs for each side of the drivetrain. Inconsistencies between sides are now equally distributes with a max of +-4in/s while throttling. Not sure how to fix the gap further but will test to see if the error is tolerable
