### ISSUE TITLE
Ensure encoders can be unplugged during a match

### ISSUE THREAD

**Issue by aswerdlow935** [Milken-Computer-Science/MilkenKnights-PowerUp#9]
Ensure code does not crash and required subsystems switch to open loop mode.

**Comment by AustinShalit** [comment]
Just to confirm, you are talking about encoders plugged into the talon or roborio?  If you are talking about "dumb" encoders, how do you do this?

**Comment by aswerdlow935** [comment]
Talking about mag encoders (plugged into the talon). Motion Magic on the Arm now works when an encoder is unplugged (simply switches to Open_Loop), but still need to test and ensure that Drive continues to work. Hopefully this year we won't have the robot running into the wall thinking that the position is '0'

**Comment by AustinShalit** [comment]
That is reasonable.  I would work on a way that the drivers know it has revered to open loop mode.

Make sure electrical know to not let this happen.

**Comment by aswerdlow935** [comment]
Ya hopefully with mag encoders it'll be hard to screw things up...The only was I can think of notifying the drivers is by A)just having them test the joystick if the arm every stops responding to the buttons or B)Putting something in shuffleboard (but it's a bit difficult to read a piece of text during a match)

**Comment by AustinShalit** [comment]
shuffleboard does support boolean values that show up as big colored boxes.  You could have a 'status' box that is green when stuff is working, red otherwise.

**Comment by aswerdlow935** [comment]
🧐will do that...Tested unplugged encoder in drive and the talon simply ignores the PID and works perfectly off of feedforward. Added an encoder disabled boolean that is sent to the TrajectoryFollower class and disables the position follower, but still need to fix the isPathDone in case of encoder disconnect. I think that if a path is already running that we should continue in case of encoder disconnect, but if it happens before start, switch to either a drive straight or drive straight then place in switch.

**Comment by alexanderswerdlow** [comment]
Currently the method in MkTalon to check encoder health is broken
